apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-demo-deployment
  labels:
    app: api-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-demo
  template:
    metadata:
      labels:
        app: api-demo
    spec:
      containers:
      - name: api-demo
        image: brs/demo:0.1
        ports:
        - containerPort: 8080